const state={sheets:[],current:null,rows:[]};
const pivot=[['01 SUMATERA',1,145,47,123,41,493,59,4,20,0,139,80,29,1,4,3,16,15,3,2],['02 JABO/JABAR',2,257,118,181,38,909,50,8,14,1,205,148,81,41,5,9,27,15,5,2],['03 JATENG/JATIM',0,91,5,41,13,295,3,5,1,0,23,22,9,2,0,1,2,2,1,0],['04 KALIMANTAN',0,11,2,8,9,33,0,0,1,0,1,0,0,1,0,0,0,3,0,0],['05 SULAWESI',0,13,1,3,11,77,1,0,4,0,5,4,4,0,0,0,1,1,0,0],['06 NUSRA',0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],['07 MALUKU',0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0]];
const pheads=['Region','NUT','Yardlamp','OBL','Foto Cell','Padlock Kombinasi','Padlock','Pilox Karat','Pole KWH','Mika KWH','Pol ACPDB','Arrester','COS','BUSBAR','Grounding','Splitzen','Box Control','Fondasi','Pagar','Kawat duri','KABEL'];
function $(x){return document.querySelector(x)}
function login(){localStorage.setItem('pm_logged','1');$('#login').classList.add('hidden');$('#app').classList.remove('hidden');$('#who').textContent=localStorage.getItem('pm_user')||'admin';loadSheets()}
$('#loginForm').addEventListener('submit',e=>{e.preventDefault();if($('#user').value==='admin'&&$('#pass').value==='admin123'){localStorage.setItem('pm_user',$('#user').value);login()}else $('#loginErr').textContent='Username atau password salah.'});
$('#logout').onclick=()=>{localStorage.removeItem('pm_logged');location.reload()};
async function loadSheets(){state.sheets=await fetch('data/sheets.json').then(r=>r.json());buildNav();showDashboard()}
function buildNav(){const nav=$('#nav');nav.innerHTML='<div class="nav-group">Utama</div><button data-page="dashboard">▦ Dashboard</button><button data-page="process">⚡ Flow Imbas Petir</button><div class="nav-group">Data Excel</div>'+state.sheets.map(s=>`<button data-sheet="${s.id}">${escapeHtml(s.name)}</button>`).join('');nav.querySelectorAll('button').forEach(b=>b.onclick=()=>b.dataset.page?b.dataset.page==='dashboard'?showDashboard():showProcess():showSheet(+b.dataset.sheet))}
function setTitle(t){$('#pageTitle').textContent=t;document.querySelectorAll('nav button').forEach(x=>x.classList.remove('active'))}
function showDashboard(){setTitle('Dashboard');$('#content').innerHTML=`<div class="grid"><div class="card kpi"><div class="label">Total region</div><div class="value">7</div><div class="sub">Dari data PIVOT</div></div><div class="card kpi"><div class="label">Total Padlock</div><div class="value">1,807</div><div class="sub">Rekap seluruh region</div></div><div class="card kpi"><div class="label">Yardlamp</div><div class="value">517</div><div class="sub">Rekap seluruh region</div></div><div class="card kpi"><div class="label">Arrester</div><div class="value">373</div><div class="sub">Rekap seluruh region</div></div></div><div class="panel card"><h2>Rekap PIVOT per Region</h2><div class="tablewrap"><table><thead><tr>${pheads.map(h=>`<th>${h}</th>`).join('')}</tr></thead><tbody>${pivot.map(r=>'<tr>'+r.map(v=>`<td>${v}</td>`).join('')+'</tr>').join('')}</tbody></table></div></div><div class="panel card"><h2>Informasi</h2><p class="muted">Data utama diambil dari workbook Excel yang diberikan. Gunakan menu <b>Data Excel</b> untuk membuka sheet dan melakukan pencarian.</p></div>`}
function showProcess(){setTitle('Flow Process Imbas Petir');const steps=['Info Sambaran Petir dari PIC/Koordinator','Admin Kirim Form pendataan Imbas Petir Ke PIC','PIC melakukan Pendataan dan mengirim hasilnya ke admin','Admin mendapatkan Data Kronologi kejadian dan Rincian Elektronik warga dari PIC','Admin melakukan pengecekan dan rekap data','Data diteruskan untuk proses penanganan','Update status sampai pekerjaan selesai'];$('#content').innerHTML='<div class="process">'+steps.map((s,i)=>`<div class="step"><div class="num">${i+1}</div><div class="card">${s}</div></div>`).join('')+'</div>'}
async function showSheet(id){const s=state.sheets.find(x=>x.id===id);setTitle(s.name);$('#content').innerHTML=`<div class="panel card"><div class="toolbar"><input id="q" placeholder="Cari di sheet..."><span class="muted">${s.rows.toLocaleString()} baris · ${s.cols} kolom · ${s.dimension}</span></div><div class="tablewrap" id="tw"><div class="muted" style="padding:18px">Memuat data...</div></div></div>`;const text=await fetch(s.file).then(r=>r.text());state.rows=parseCSV(text);renderRows(state.rows);$('#q').oninput=e=>renderRows(state.rows,e.target.value)}
function parseCSV(t){let rows=[],row=[],cell='',quote=false;for(let i=0;i<t.length;i++){let c=t[i];if(c==='"'){if(quote&&t[i+1]==='"'){cell+='"';i++}else quote=!quote}else if(c===','&&!quote){row.push(cell);cell=''}else if((c==='\n'||c==='\r')&&!quote){if(c==='\r'&&t[i+1]==='\n')i++;row.push(cell);rows.push(row);row=[];cell=''}else cell+=c}if(cell||row.length){row.push(cell);rows.push(row)}return rows}
function renderRows(rows,q=''){const max=250;let filtered=rows.slice(0,1).concat(rows.slice(1).filter(r=>!q||r.some(v=>String(v).toLowerCase().includes(q.toLowerCase()))).slice(0,max));if(!filtered.length)return;$('#tw').innerHTML='<table><thead><tr>'+filtered[0].map((h,i)=>`<th>${escapeHtml(h||('C'+i))}</th>`).join('')+'</tr></thead><tbody>'+filtered.slice(1).map(r=>'<tr>'+r.map(v=>`<td>${escapeHtml(v)}</td>`).join('')+'</tr>').join('')+'</tbody></table><div class="muted" style="padding:8px 10px">Menampilkan maksimal ${max} hasil untuk menjaga performa browser.</div>'}
function escapeHtml(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
if(localStorage.getItem('pm_logged')==='1')login();
